name: C/C++ CI

on:
  push:
    branches: [ "master", "test" ]
  pull_request:
    branches: [ "master", "test" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: install deps
      run: sudo apt install -y meson ninja-build libfmt-dev
    - name: configure
      run: meson -Dpyv4l2=enabled -Dwerror=true -Db_lto=true build
    - name: build
      run: ninja -v -C build
